name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Build report artifact
        run: make report
      - name: Freshness gate
        if: ${{ github.event_name == 'schedule' || (github.event_name != 'schedule' && startsWith(github.ref, 'refs/heads/')) }}
        env:
          RUN_DATE: ${{ github.run_started_at }}
        run: |
          import os
          from datetime import datetime, timezone

          run_ts = datetime.fromisoformat("${{ github.run_started_at }}".replace("Z", "+00:00"))
          if run_ts.month == 10 and run_ts.day in (29, 30):
              import subprocess
              subprocess.run(["make", "check-fresh"], check=True)
          else:
              print("Freshness gate skipped (outside Oct 29-30 window).")
        shell: python
      - name: Upload memo and figures
        uses: actions/upload-artifact@v4
        with:
          name: report-assets
          path: |
            build/memo/report.md
            build/figures
